import { chromium } from "playwright";
const app = "https://marvelous-dinosaur-465.convex.site/";
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs = []; p.on("pageerror", e => errs.push(String(e)));
await p.goto(app, { waitUntil: "networkidle" });
await p.getByRole("button", { name: /try it now/i }).first().click();
await p.waitForURL(/#\/board\//, { timeout: 30000 }); await p.waitForTimeout(2500);
await p.getByRole("button", { name: /try a real change/i }).first().click();
await p.waitForTimeout(12000);
const pub = p.getByRole("button", { name: /publish a fee/i });
await pub.waitFor({ state: "visible", timeout: 30000 });
await pub.click();
await p.waitForTimeout(800);
const btn = p.locator("[data-pigeon-check]").first();
console.log("right after publish:", (await btn.textContent())?.trim(), "disabled:", await btn.isDisabled());
if (!(await btn.isDisabled())) await btn.click();
await p.waitForTimeout(1500);
let body = await p.textContent("body");
console.log("ServerError:", body.includes("Server Error"), "| note:", body.match(/Checked [^.]*\. Try again in a minute\.|A check is already running\./)?.[0] ?? "(none)");
await p.waitForTimeout(25000);
await btn.click(); await p.waitForTimeout(1500);
body = await p.textContent("body");
console.log("second click -> note:", body.match(/Checked [^.]*\. Try again in a minute\.|A check is already running\./)?.[0] ?? "(none)", "| ServerError:", body.includes("Server Error"));
console.log("summary present:", /money, dates or availability|act now|worth a look/.test(body));
await p.screenshot({ path: "../shots/checknow-fixed.png" });
console.log("pageerrors:", errs);
await b.close();
